"""Compatibility tests for pytest_generate_tests hook with pytest-swarm."""

from __future__ import annotations

import pytest


# ---------------------------------------------------------------------------
# Helpers shared across tests
# ---------------------------------------------------------------------------

def _read(path) -> list[str]:
    return path.read_text().splitlines() if path.exists() else []


# ---------------------------------------------------------------------------
# Direct (non-indirect) parametrization — parallel full path
# ---------------------------------------------------------------------------

class TestDirectParametrize:
    """pytest_generate_tests with non-indirect params → parallel full path."""

    def test_basic_params_run_and_pass(self, pytester):
        """Items generated by pytest_generate_tests are run and pass."""
        pytester.makeconftest("""
def pytest_generate_tests(metafunc):
    if "n" in metafunc.fixturenames:
        metafunc.parametrize("n", range(4))
""")
        pytester.makepyfile("""
import pytest

@pytest.mark.swarm
def test_items(n):
    assert n in range(4)
""")
        pytester.runpytest().assert_outcomes(passed=4)

    def test_values_forwarded_correctly(self, pytester, tmp_path):
        """Each generated parameter value is actually forwarded to the test body."""
        log = tmp_path / "seen.txt"
        pytester.makeconftest(f"""
def pytest_generate_tests(metafunc):
    if "val" in metafunc.fixturenames:
        metafunc.parametrize("val", ["x", "y", "z"])
""")
        pytester.makepyfile(f"""
import pytest

@pytest.mark.swarm
def test_items(val):
    with open({str(log)!r}, "a") as f:
        f.write(val + "\\n")
""")
        pytester.runpytest().assert_outcomes(passed=3)
        assert sorted(_read(log)) == ["x", "y", "z"]

    def test_conftest_generate_tests(self, pytester):
        """pytest_generate_tests defined in conftest (plugin-style) works."""
        pytester.makeconftest("""
def pytest_generate_tests(metafunc):
    if "idx" in metafunc.fixturenames:
        metafunc.parametrize("idx", [10, 20, 30])
""")
        pytester.makepyfile("""
import pytest

@pytest.mark.swarm
def test_items(idx):
    assert idx in (10, 20, 30)
""")
        pytester.runpytest().assert_outcomes(passed=3)

    def test_all_items_collected_and_run(self, pytester, tmp_path):
        """All N generated items are collected and each runs exactly once."""
        log = tmp_path / "runs.txt"
        pytester.makeconftest(f"""
def pytest_generate_tests(metafunc):
    if "n" in metafunc.fixturenames:
        metafunc.parametrize("n", range(6))
""")
        pytester.makepyfile(f"""
import pytest

@pytest.mark.swarm
def test_items(n):
    with open({str(log)!r}, "a") as f:
        f.write(str(n) + "\\n")
""")
        pytester.runpytest().assert_outcomes(passed=6)
        assert sorted(int(x) for x in _read(log)) == list(range(6))


# ---------------------------------------------------------------------------
# Indirect parametrization — one broad-scope instance per parameter value
# ---------------------------------------------------------------------------

class TestIndirectParametrize:
    """pytest_generate_tests with indirect=True."""

    def test_indirect_runs_and_passes(self, pytester):
        """Indirect params via pytest_generate_tests reach every item intact."""
        pytester.makeconftest("""
def pytest_generate_tests(metafunc):
    if "fix" in metafunc.fixturenames:
        metafunc.parametrize("fix", ["a", "b", "c"], indirect=True)
""")
        pytester.makepyfile("""
import pytest

@pytest.fixture
def fix(request):
    return request.param.upper()

@pytest.mark.swarm
def test_items(fix):
    assert fix in ("A", "B", "C")
""")
        pytester.runpytest().assert_outcomes(passed=3)

    def test_indirect_values_forwarded(self, pytester, tmp_path):
        """request.param is correct for each indirectly parametrized item."""
        log = tmp_path / "log.txt"
        pytester.makeconftest(f"""
def pytest_generate_tests(metafunc):
    if "fix" in metafunc.fixturenames:
        metafunc.parametrize("fix", ["p", "q", "r"], indirect=True)
""")
        pytester.makepyfile(f"""
import pytest

@pytest.fixture
def fix(request):
    return request.param

@pytest.mark.swarm
def test_items(fix):
    with open({str(log)!r}, "a") as f:
        f.write(fix + "\\n")
""")
        pytester.runpytest().assert_outcomes(passed=3)
        assert sorted(_read(log)) == ["p", "q", "r"]

    def test_indirect_module_scope_fixture(self, pytester):
        """Indirect params on a module-scope fixture get one instance per value."""
        pytester.makeconftest("""
def pytest_generate_tests(metafunc):
    if "mod_fix" in metafunc.fixturenames:
        metafunc.parametrize("mod_fix", [1, 2, 3], indirect=True)
""")
        pytester.makepyfile("""
import pytest

@pytest.fixture(scope="module")
def mod_fix(request):
    return request.param * 10

@pytest.mark.swarm
def test_items(mod_fix):
    assert mod_fix in (10, 20, 30)
""")
        pytester.runpytest().assert_outcomes(passed=3)


# ---------------------------------------------------------------------------
# Combined with @pytest.mark.parametrize
# ---------------------------------------------------------------------------

class TestCombinedWithMark:
    """pytest_generate_tests and @pytest.mark.parametrize together."""

    def test_cartesian_product_runs(self, pytester):
        """Cartesian product of pytest_generate_tests and @pytest.mark.parametrize runs."""
        pytester.makeconftest("""
def pytest_generate_tests(metafunc):
    if "x" in metafunc.fixturenames:
        metafunc.parametrize("x", [1, 2])
""")
        pytester.makepyfile("""
import pytest

@pytest.mark.swarm
@pytest.mark.parametrize("y", ["a", "b"])
def test_items(x, y):
    assert x in (1, 2)
    assert y in ("a", "b")
""")
        # 2 x values × 2 y values = 4 items
        pytester.runpytest().assert_outcomes(passed=4)

    def test_cartesian_product_values_correct(self, pytester, tmp_path):
        """Every (x, y) combination is seen exactly once."""
        log = tmp_path / "log.txt"
        pytester.makeconftest(f"""
def pytest_generate_tests(metafunc):
    if "x" in metafunc.fixturenames:
        metafunc.parametrize("x", [0, 1])
""")
        pytester.makepyfile(f"""
import pytest

@pytest.mark.swarm
@pytest.mark.parametrize("y", ["a", "b"])
def test_items(x, y):
    with open({str(log)!r}, "a") as f:
        f.write(f"{{x}}{{y}}\\n")
""")
        pytester.runpytest().assert_outcomes(passed=4)
        assert sorted(_read(log)) == ["0a", "0b", "1a", "1b"]


# ---------------------------------------------------------------------------
# Interaction with fixtures
# ---------------------------------------------------------------------------

class TestWithFixtures:
    """pytest_generate_tests combined with regular fixtures."""

    def test_param_alongside_fixture(self, pytester):
        """A generate_tests param coexists with a regular function-scope fixture."""
        pytester.makeconftest("""
def pytest_generate_tests(metafunc):
    if "n" in metafunc.fixturenames:
        metafunc.parametrize("n", range(3))
""")
        pytester.makepyfile("""
import pytest

@pytest.fixture
def double(n):
    return n * 2

@pytest.mark.swarm
def test_items(n, double):
    assert double == n * 2
""")
        pytester.runpytest().assert_outcomes(passed=3)

    def test_param_alongside_session_fixture(self, pytester):
        """A generate_tests param coexists with a session-scope fixture."""
        pytester.makeconftest("""
import pytest

@pytest.fixture(scope="session")
def sess():
    return 100

def pytest_generate_tests(metafunc):
    if "n" in metafunc.fixturenames:
        metafunc.parametrize("n", range(3))
""")
        pytester.makepyfile("""
import pytest

@pytest.mark.swarm
def test_items(n, sess):
    assert sess == 100
    assert n in range(3)
""")
        pytester.runpytest().assert_outcomes(passed=3)

    def test_generate_tests_with_autouse_fixture(self, pytester, tmp_path):
        """An autouse fixture is invoked for every generate_tests-parametrized item."""
        log = tmp_path / "log.txt"
        pytester.makeconftest(f"""
import pytest

@pytest.fixture(autouse=True)
def counter():
    with open({str(log)!r}, "a") as f:
        f.write("1\\n")

def pytest_generate_tests(metafunc):
    if "n" in metafunc.fixturenames:
        metafunc.parametrize("n", range(4))
""")
        pytester.makepyfile("""
import pytest

@pytest.mark.swarm
def test_items(n):
    pass
""")
        pytester.runpytest().assert_outcomes(passed=4)
        assert len(_read(log)) == 4


# ---------------------------------------------------------------------------
# Hook compatibility: public pytest hooks fire for generate_tests items
# ---------------------------------------------------------------------------

class TestHooksWithGenerateTests:
    """Public hooks must fire correctly for items from pytest_generate_tests."""

    def test_logreport_fires_for_all_phases(self, pytester, tmp_path):
        """pytest_runtest_logreport fires for setup/call/teardown for each item."""
        log = tmp_path / "log.txt"
        pytester.makeconftest(f"""
import pytest

@pytest.hookimpl
def pytest_runtest_logreport(report):
    with open({str(log)!r}, "a") as f:
        f.write(report.when + "\\n")

def pytest_generate_tests(metafunc):
    if "n" in metafunc.fixturenames:
        metafunc.parametrize("n", range(3))
""")
        pytester.makepyfile("""
import pytest

@pytest.mark.swarm
def test_items(n):
    pass
""")
        pytester.runpytest().assert_outcomes(passed=3)
        calls = _read(log)
        assert len(calls) == 9
        assert calls.count("setup") == 3
        assert calls.count("call") == 3
        assert calls.count("teardown") == 3

    def test_skip_works_with_generate_tests(self, pytester):
        """pytest.mark.skip is honoured for items from pytest_generate_tests."""
        pytester.makeconftest("""
def pytest_generate_tests(metafunc):
    if "n" in metafunc.fixturenames:
        metafunc.parametrize("n", range(3))
""")
        pytester.makepyfile("""
import pytest

@pytest.mark.swarm
@pytest.mark.skip(reason="skipped")
def test_items(n):
    pass
""")
        pytester.runpytest().assert_outcomes(skipped=3)

    def test_xfail_works_with_generate_tests(self, pytester):
        """pytest.mark.xfail is honoured for items from pytest_generate_tests."""
        pytester.makeconftest("""
def pytest_generate_tests(metafunc):
    if "n" in metafunc.fixturenames:
        metafunc.parametrize("n", range(3))
""")
        pytester.makepyfile("""
import pytest

@pytest.mark.swarm
@pytest.mark.xfail
def test_items(n):
    assert False
""")
        pytester.runpytest().assert_outcomes(xfailed=3)